[package]
name = "plonky2-task"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
plonky2 = "=0.1.3"
plonky2_crypto = "0.1"
hex = "0.4"

[patch.crates-io]
plonky2_crypto = { path = "plonky2-crypto" }
